# Generated by Django 4.1.5 on 2023-01-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('diskounted_price', models.FloatField()),
                ('discription', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('OP', 'Огнетушители ОП (Порошковые)'), ('OU', 'Огнетушители ОУ (углекислотные)'), ('OV', 'Воздушно-пенные огнетушители (ОВП)'), ('PSh', 'Пожарные шкафы, люки, рамы для шкафов'), ('ShP', 'Щиты пожарные, стенды'), ('RP', 'Рукава пожарные'), ('PT', 'Пожарно-техническое оснащение'), ('PA', 'Противопожарная арматура'), ('SIZ', 'Все виды СИЗ (средства индивидуальной защиты)'), ('PO', 'Перезарядка Огнетушителей ОП (порошковые)'), ('YP', 'Ящики для песка'), ('PK', 'Пожарное обмундирование и комплектующие'), ('KP', 'Клапаны пожарных кранов'), ('GP', 'Генераторы пены средней кратности'), ('MS', 'Монтаж системы противопожарной сигнализации')], max_length=4)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
